apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: say-hello
      image: debian:stable-slim
      command:
        - /bin/bash
      args: ['-c', 'echo Hello World']
